name: isolate_handler_example
description: Demonstrates how to use the isolate_handler plugin.
publish_to: none
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  isolate_handler:
    path: ../
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

dev_dependency_overrides:
  isolate_handler:
    path: ../

flutter:
  uses-material-design: true
