name: isolate_handler
description: Effortless isolates abstraction layer with support for inter-isolate communication.
version: 1.0.2
homepage: https://github.com/deakjahn/isolate_handler
documentation: https://github.com/deakjahn/isolate_handler/blob/0.2.0/README.md
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_isolate: 
    git: https://github.com/sumitsharansatsangi/flutter_isolate.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2